export default {
  name: '日期时间组件',
  config: {
    type: 'datetime',
    conponentType: 'datetime',
    label: '日期',
    labelWidth: '',
    defaultValue: '',
    // format: new Date().getTime().toString(),
    placeholder: '请选择日期时间',
    inputFormat: 'yyyy-MM-dd HH:mm:ss',
    // prpperClass: 'DatePicker',
    size: 'small',
    prefixIcon: '',
    'clear-icon': 'el-icon-close',
    align: 'left',
    startPlaceholder: '',
    endPlaceholder: '',
    'range-separator': '-',
    labelTips: '',
    delimiter: ',',
    isRange: false,
    required: false,
    clearable: true,
    editable: true,
    readonly: false,
    disabled: false,
    'validate-event': true,
    validations: '',
    checkedInfo: '请选择日期时间',
    isFormat: false,
    events: [],
    style: {}
  }
}
